### ISSUE TITLE
Fix feed timer

### ISSUE THREAD

**Issue by glciampaglia** [glciampaglia/Rockwell#88]
In #72 we introduced a delay of 30s at the end of the feed before the "next" button becomes available. The original idea was to make sure that the user does not race through the feed. However, right now this not very effective, since the timer starts when the user has reached the end of the feed. And so the result is that one needs to wait an extra time, which is very annoying. 

For the demo, we have decided to disable this delay (we set the delay to 0 seconds). To implement this correctly, we need a flag that is initially set to false, and should have an asynchronous process/thread sleeping for 30 seconds when the feed is loaded. When the process/thread wakes up, it should check that the user is at the bottom of the feed. If that is the case, it can enable the button. If that is not the case, the process/thread should just flip the flag, and when the user has reached the end of the feed, if the flag has been flipped, then the button can be enabled immediately.

**Comment by glciampaglia** [comment]
We decided we will implement the correct functionality directly in React.

**Comment by glciampaglia** [comment]
We have this mostly implemented. We simply need to make sure that the "Next" button is displayed as a button (currently, it is displayed as a link).

**Comment by RobertAndion** [comment]
This is now complete
